name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # or whatever branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/aws-deploy2
            git pull origin main
            cd frontend
            npm install
            npm run build
            cd ../backend
            npm install
            pm2 restart mern-app || pm2 start server.js --name "mern-app"
